[package]
name = "augment"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.release]
lto = true
strip = true
panic = "abort"

[profile.trace]
inherits = "release"
debug = true
strip = "none"
# split-debuginfo = "packed"

[lints.clippy]
needless_return = "allow"